### ISSUE TITLE
Is Bluetooth turned on?

### ISSUE THREAD

**Issue by JonasWho** [Artirigo/react-native-kontaktio#1]
Is there a way to check if the Bluetooth is even turned on on the device?

**Comment by Andruschenko** [comment]
You can use our fork of `react-native-bluetooth-state`: https://github.com/Artirigo/react-native-bluetooth-state

**Comment by Andruschenko** [comment]
I'll close the issue since it covers a feature not intended for this package.

**Comment by JonasWho** [comment]
@Andruschenko ok, thx!
