### ISSUE TITLE
Support for iOS

### ISSUE THREAD

**Issue by jo2010** [Artirigo/react-native-kontaktio#12]
Missing support for iOS. Any idea when the support will be added?

**Comment by Andruschenko** [comment]
I'm working on it! It should be done by mid April.

**Comment by Andruschenko** [comment]
Update: iOS version is available for first tests here on another branch: https://github.com/Artirigo/react-native-kontaktio/tree/link-kontakt-module

Will be merged into the master branch and released to npm soon after it is properly tested.

**Comment by Andruschenko** [comment]
iOS version is merged to master now as of version 2.0.0
