### ISSUE TITLE
isConnected fails i connect() has not been called

### ISSUE THREAD

**Issue by JonasWho** [Artirigo/react-native-kontaktio#15]
Since we have multiple places in our codebase where `connect()` can be called from, we would like a way to check whether or not the proximity manager has been initialised. 
I tried using `isConnected()`, but it throws an exception if called before `connect()`.

Am I doing it wrong or should `isConnected()` also do a check for `beaconProximityManager == null`?

**Comment by Andruschenko** [comment]
I fixed the issue on branch `bug/isConnected-error`. I just didn't have the right cable with me and couldn't test it. Perhaps you could give it a short test run and I'll then merge it to master.

**Comment by JonasWho** [comment]
Perfect, thanks! It works like a charm now :)
