### ISSUE TITLE
Error using Expo SDK in React Native project

### ISSUE THREAD

**Issue by AndreaZanuccoli** [Artirigo/react-native-kontaktio#23]
Hi,
in my React Native project your sdk works great, but when i install Expo sdk (https://expo.io/) inside the project and launch it on my devices it appear this error on iOS:
![img_9302](https://user-images.githubusercontent.com/34231016/33545879-cb22a520-d8df-11e7-818d-8f3236070082.PNG)

And `undefined is not a object (evaluating 'KontaktModule.disconnet)` on Android.
Have you got any solution to avoid this problem?

**Comment by rgstephens** [comment]
Expo doesn't support Bluetooth yet. You'll find some references to this in the expo issues list.

**Comment by AndreaZanuccoli** [comment]
Thank you for the information, i was not aware of it
