### ISSUE TITLE
Could not determine java version from '9.0.1'.

### ISSUE THREAD

**Issue by didacus** [Artirigo/react-native-kontaktio#28]
Has anyone come across this issue? If so, let me know the solution.
I get the error when running 'react-native run-android'.

Thank you in advance.

**Comment by ca057** [comment]
I had the same issue with Java9, could only get a RN project running with Java8. Might be related to https://github.com/facebook/react-native/issues/16536

Can you confirm it is working with Java8?

**Comment by didacus** [comment]
Yes, we managed to fix by installing a compatible version of java. Thank you.

**Comment by pashute** [comment]
so please close this issue
