### ISSUE TITLE
const connect already defined

### ISSUE THREAD

**Issue by pashute** [Artirigo/react-native-kontaktio#39]
I have 

     import { connect } from 'react-redux';

And then: 

    import Kontakt from 'react-native-kontaktio';
    const {  connect, configure, disconnect. startScanning, setBeaconReagons ... 

But I get an ESLint error:  connect is already defined. And rightly so, no?

I tried 

    import { connect as connectKontakt, configure, disconnect, startScanning, setBeaconReagons...

But that gives me:  Possible Unhandled Promise  Rejection (reactNativeKontaktio.connect) is not a function. 

What should/can I do?

Please see https://stackoverflow.com/questions/51589676/es6-how-to-import-already-defined-in-another-js-package

**Comment by ca057** [comment]
Right, having two variables named `connect` shouldn't work. Regardless of that, can you give some more context  - eslint version & setup?

Haven't tried it locally, but what might work is something like the following (renaming the property you destructure from the Kontakt object):
```javascript
import { connect } from 'react-redux';
import Kontakt from 'react-native-kontaktio';

const { connect: connectKontatkt, configure /* ... all the other things you need from RNKontakt */ } = Kontakt;
```

**Comment by pashute** [comment]
Thank you!!

Meanwhile I changed the other (redux) constant by calling

    import { connect as reduxConnect } from 'react-redux';

and that worked. But had to change my redux code a tiny bit.

>

**Comment by pashute** [comment]
Thank you!!

Meanwhile I changed the other (redux) constant by calling

    import { connect as reduxConnect } from 'react-redux';

and that worked. But had to change my redux code a tiny bit.
