### ISSUE TITLE
Beacons are ranged without valid Kontakt.io API key

### ISSUE THREAD

**Issue by Andruschenko** [Artirigo/react-native-kontaktio#5]
Tried example with default `MY_KONTAKTIO_API_KEY` and ranged my Kontakt.io beacons

**Comment by Andruschenko** [comment]
I thought reason might be that the default Kontakt.io UUID (`f7826da6-4fa2-4e98-8024-bc5b71e0893e`) was used while testing. But using a different UUID also didn't require the correct API key.

**Comment by Andruschenko** [comment]
After getting feedback from Kontakt.io: The Konakt.io API Key is not necessary for ranging and monitoring, it is required to communicate with the Kontakt.io cloud especially for shuffling functionalities and battery level monitoring.

**Comment by arunraj-qburst** [comment]
How did I get the light data available in the telemetry object?
I am using 'react-native-kontaktio' + eddystone with the beacon side. Beacons are light sensor enabled (Bluvision). I could not find any information related to light in the kontaktio repo (https://libraries.io/github/Andruschenko/react-native-kontaktio)
Any guidance in this regard would be greatly appreciated.
